setup protractor configuration
Karenduque/protractor-workshop-2018 pull request #1
Opened 2019-01-13 20:22 UTC by Karenduque

2019-01-13 20:42 UTC, aperdomob requested changes

2019-01-13 20:42 UTC, aperdomob commented on .gitignore
> +awesome-report
por que esto?

2019-01-13 20:42 UTC, aperdomob commented on LICENSE
> +Copyright (c) 2019 Agile Testing Colombia
En esta línea va tu nombre en vez de Agile Testing Colombia

2019-01-13 20:42 UTC, aperdomob commented on package.json
> +	"clean": "rm -rf dist",
esta mal indentado esta linea

2019-01-13 20:42 UTC, aperdomob commented on protractor/local.config.ts
> +};
EOF

2019-01-13 20:42 UTC, aperdomob commented on test/google.spec.ts
> +});
EOF

2019-01-13 20:42 UTC, aperdomob commented on tsconfig.json
> +}
EOF

2019-01-14 14:03 UTC, Karenduque commented on .gitignore
> +awesome-report
lo cambie por 
# Typescript
dist

2019-01-14 14:03 UTC, Karenduque commented on .gitignore
> +awesome-report
ok, si, se quito "awesome-report"

2019-01-14 14:04 UTC, Karenduque commented on LICENSE
> +Copyright (c) 2019 Agile Testing Colombia
si, modificado.

2019-01-14 14:05 UTC, Karenduque commented on package.json
> +	"clean": "rm -rf dist",
si, modificado.

2019-01-14 14:10 UTC, Karenduque commented on protractor/local.config.ts
> +};
okis,

2019-01-14 14:11 UTC, Karenduque commented on test/google.spec.ts
> +});
okis

2019-01-14 14:11 UTC, Karenduque commented on tsconfig.json
> +}
okis

2019-01-14 15:09 UTC, aperdomob approved these changes

2019-01-14 16:30 UTC, merged